### ISSUE TITLE
Test runner failing

### ISSUE THREAD

**Issue by marfrit** [ba-st/Willow-Playground#37]
When I create a new 32-bit Pharo 6.1 image and then load the Willow Playground, subsequently start the Presentation "Smalltalks2017Presentation start" - and then navigate to http://localhost:8080/test-runner-bootstrap3 - I get an endless spinner. Looking at the console, I see 

SubscriptOutOfBounds: 14
Your request could not be completed. An exception occurred.

for two resources.

**Comment by gcotelli** [comment]
Already Fixed in v8
