### ISSUE TITLE
Image saved in GH releases for v8.1.0-Pharo64-7.0 Unusable on pharo 7 64bits 

### ISSUE THREAD

**Issue by MattFerzz** [ba-st/Willow-Playground#41]
After downloading the image and triying to run it on a Pharo 7 64bits VM almost everything in the VM crashes with the attached error:
![image](https://user-images.githubusercontent.com/28680454/62621666-dd8b4880-b8f2-11e9-8335-1e171dbbe388.png)
(Running Xubuntu x64, also tried on windows 10 x64)

**Comment by gcotelli** [comment]
It's a problem with the artifacts saved by the CI into the releases page. Loading the code in your own image works Ok.

**Comment by gcotelli** [comment]
Pre-built images are no longer saved to the release.
