### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by Shaping** [ba-st/Willow-Playground#42]
The preloaded 64-bit image doesn't work.  There are many walkbacks.  It's mostly unusable.

Instead, when I load Willow via

Metacello new
	baseline: 'Willow';
	repository: 'github://ba-st/Willow:release-candidate/source';
	load.

into a fresh Pharo 8 image,  I cannot eval expression

Smalltalks2017Presentation start

because Smalltalks2017Presentation is not present.

No additional instructions are given for starting a server.  Thus none of the tutorial URLs can be used.

**Comment by gcotelli** [comment]
Hi @Shaping , you need to load Willow-Playground to [get the examples](https://github.com/ba-st/Willow-Playground/blob/release-candidate/docs/Installation.md):
```
Metacello new
	baseline: 'WillowPlayground';
	repository: 'github://ba-st/Willow-Playground:release-candidate/source';
	load.
```
Your loading code are only loading the base support for Willow.

I will check the saved image. Probably it was created when Pharo 8 was still a moving target, now that it's released we can have a compatible image.

**Comment by gcotelli** [comment]
The server startup is baked in `Smalltalks2017Presentation start`

**Comment by Shaping** [comment]
Hi.

 

We probably want to have a clean distinct sequence of instructions in each case, especially in the case of the prebuilt image, like where also to get the vm if you can’t use the scripts.   I can’t use the scripts without fixing WSL, and I prefer not to do that now.

 

I have the latest Pharo Launcher installed and I’m using Pharo 8 64-bit.  If you have instructions for loading and using watching the ESUG Willow demo in Pharo 8, that would be great.

 

Generally, I’m evaluating Seaside with Willow and comparing it to AIDAweb.  What happened to AIDAweb?  It seems like a very useful architecture, but little if any new work is now done with it.

 

Shaping

**Comment by Shaping** [comment]
The following Willow playground image was launched from the latest Pharo Launcher 2.0 (I assume it is ready for use):

 



 

When will the Willow demo be working in Pharo 8 or later?

 

When will Willow be ready for production?  I’m assuming that it is not because the demo is broken.  Clicking on any node in the tree above cause a walkback.

 

 

Shaping

 

-------- ---

Hi.

 

We probably want to have a clean distinct sequence of instructions in each case, especially in the case of the prebuilt image, like where also to get the vm if you can’t use the scripts.   I can’t use the scripts without fixing WSL, and I prefer not to do that now.

 

I have the latest Pharo Launcher installed and I’m using Pharo 8 64-bit.  If you have instructions for loading and using watching the ESUG Willow demo in Pharo 8, that would be great.

 

Generally, I’m evaluating Seaside with Willow and comparing it to AIDAweb.  What happened to AIDAweb?  It seems like a very useful architecture, but little if any new work is now done with it.

 

Shaping

**Comment by Shaping** [comment]
Hi Gabriel.

 

Can you tell me whether the latest version of Seaside and Willow in the Cincom Store works as well as those in Pharo?

 

 

Shaping

 

---------------

 

The following Willow playground image was launched from the latest Pharo Launcher 2.0 (I assume it is ready for use):

 



 

When will the Willow demo be working in Pharo 8 or later?

 

When will Willow be ready for production?  I’m assuming that it is not because the demo is broken.  Clicking on any node in the tree above cause a walkback.

 

 

Shaping

 

-------- ---

Hi.

 

We probably want to have a clean distinct sequence of instructions in each case, especially in the case of the prebuilt image, like where also to get the vm if you can’t use the scripts.   I can’t use the scripts without fixing WSL, and I prefer not to do that now.

 

I have the latest Pharo Launcher installed and I’m using Pharo 8 64-bit.  If you have instructions for loading and using watching the ESUG Willow demo in Pharo 8, that would be great.

 

Generally, I’m evaluating Seaside with Willow and comparing it to AIDAweb.  What happened to AIDAweb?  It seems like a very useful architecture, but little if any new work is now done with it.

 

Shaping

**Comment by gcotelli** [comment]
Hi @Shaping ,
Sorry for the late response but our quarantined life is more complicated right now. I hope to answer your inquiries:
- We didn't know there was a Willow version for Visual Works. Certainly we don't port it or have notice of someone else porting it. 
- We have a port for VA Smalltalk in use at @Mercap not published because it still depends on some private pre-requisites, but it's working on VAST 8.6.0 to 9.2, so it works on a variety of Seaside versions.
- For the public Willow was born on 2013, and it was developed privately 1 or 2 years before.
- I can tell you the framework is production ready. Is in use at @Mercap for some banking products and this year we made available https://www.mercapabbaco.com that is using it. @mtabacman also have an RPG mastering application developed with it. Certainly the most complete integration by far is with Bootstrap (ba-st/Willow-Bootstrap)
- I've just loaded the latest released version in Pharo 8 and everything seems to be working:
[Willow-Playground-Pharo-8-64bits.zip](https://github.com/ba-st/Willow-Playground/files/4500497/Willow-Playground-Pharo-8-64bits.zip)
In case you needed it here's the image and changes files, I think you can import it on Pharo launcher. 

This fixes also ba-stWillow#153

**Comment by Shaping** [comment]
Thanks Gabriel.

I'm studying jQuery DataTables.  I don't see my question above about how best to do custom formats and colorings of column data.  I'll search around for that.  That's my main impediment to moving from local client to web.  This table control is amazingly rich compared to the clunky code I have to deal with in VW.  I still need to format and color numeric data in a very specific way, and hope I can do that perhaps with a callback.   I can't afford to slow sorting by having the column data type be text.

**Comment by gcotelli** [comment]
Hi Shaping, we're using datatables in our products and it's great. We have a non-open source wrapper for it, but I think for Pharo exists an open source one. 

You can change the formatting and sorting of a column by setting a javascript function for rendering and sorting in the datatables configuration, and colour numeric data configuring some css class and adding some rules to your stylesheet. Take a look at: https://datatables.net/manual/data/renderers#Functions and https://datatables.net/manual/data/orthogonal-data

**Comment by Shaping** [comment]
Non-open source wrapper?  How do I get it?

I have a parser--a PrintConverter--in Smalltalk. I want to use that to format numbers in cells in a tree grid.  I need a callback obviously to do that.  How do I make it happen.  Do you have a specific JS component in mind?  I don't see a way to be preDrawCallback and drawCallback to call my Smalltalk method or block.  This is what happens on the local client way.  The NewDataSet instance, instead of using default printString for the object in the cell, goes to the PrintConverter instance associated with the column and asks it for the formatting string based on the input value from the cell.  These are very elaborate bits of parsing an coloring--not something I want to recode in JS.  Why isn't this part of the framework.  It seems like an obvious need to fill.  What am I missing?

**Comment by subhani009** [comment]
hi .. we would like to use willow for VA smalltalk..
metacello is not available in va smalltalk.. how to load willow framework.. do we have some procedure with monticello importer either can you elaborate the process.. i read some blog mentioning mercap.. is it third party company product ? do we have to pay for mercap.. alot confusion with the porting process to va smalltalk.. please help..
