### ISSUE TITLE
PrintConverter-style grid-column data-rendering in a web-grid widget

### ISSUE THREAD

**Issue by Shaping** [ba-st/Willow-Playground#43]
I spent a lot of time recently implementing in VW a custom PrintConverter that colors and formats numbers and fractions in very specific elaborate ways.  It was a PITA, but it's done.  Is there a way to do something similar in Willow with, I suppose, the grid available in JQuery UI?  This and one other need are the main blocks to porting to Pharo and leaving VW forever.  The other is that I need a very nice tree with nodes the fold in and out, as usual, preferably with optional s-curve easings, and also be able to format the strings for spacing and color, anyway I want, presumably by using a reference to a block in the Smalltalk, so that I can use just use the code in the PrintConverter I wrote (pass the number to appear in the cell to the Smalltalk to render a string, and display the formatted string, yet still sort on the number (not the string) for speed.  I need fast column sorting, and these tables are big, running into the 10s of thousands of lines.  Each line has about 12 fields.  

If I've not reached the relevant part of the tutorial yet, please excuse the premature question.

**Comment by gcotelli** [comment]
Answered in ba-st/Willow-Playground#42
