### ISSUE TITLE
Conflict between existing baseline BaselineOfWillow.

### ISSUE THREAD

**Issue by oswallcr** [ba-st/Willow-Playground#47]
Conflict between existing baseline BaselineOfWillow.
Great work. Congratulations
In a clean Pharo 8 image I installed Willow latest correctly.
When trying to install PlayGround.  I have a version conflict.
![Conflicto-Willow-PlayGround](https://user-images.githubusercontent.com/24613227/89337066-95af1680-d657-11ea-9d27-6b8d40a6c481.png)
Thanks

**Comment by gcotelli** [comment]
Hi @oswallcr have you tried loading a released version? When using the `release-candidate` branch sometimes it will break while we fix the dependency chain. 

I will try to take a look at this problem.

Thanks for the report.

**Comment by oswallcr** [comment]
Hi @gcotelli,  I used fresh image Pharo 8, and for Willow:
Metacello new
	baseline: 'Willow';
	repository: 'github://ba-st/Willow:release-candidate/source';
	load.

And for Bootstrap:
Metacello new
	baseline: 'WillowBootstrap';
	repository: 'github://ba-st/Willow-Bootstrap:release-candidate/source';
	load.

Cual sería la mejor configuración para instalarlo?

**Comment by gcotelli** [comment]
Fixed
